### ISSUE TITLE
"Eternal" buffs stopped disappearing after death

### ISSUE THREAD

**Issue by SuDmit** [Aurocosh/Spellwright#3]
Basically title. I don't know at which point, but somewhere in pre-hardmode in modded playthrough  death stopped clearing permanent buffs. Character was level 4, so no State Lock spell.
Mods are mainly Calamity + Fargo's Mutant & Souls & DLC (Eternity*Revengeance Mode over Expert difficulty) + Magic Storage + dozen of small ones. 

To add to this:
Adding another mod (Terraria Overhaul) did reset buffs by itself, but then after death they still do present.

**Comment by Aurocosh** [comment]
That is actually intended behavior, just undocumented. On player death some of the Rare Spell Reagents gets consumed to prevent loss of permanent buffs. It was kinda annoying to recast all of them after each death so i added this feature. It just costs some Rare Spell Reagents per one permanent buff. Most likely buffs stopped disappearing when you started carrying Rare Spell Reagents with you.

It is not particularly obvious how that works, so i reworked it a little in version 0.8.3.6. I removed this feature and added it as a separate spell - Cycle of Eternity. It works more or less the same, but now you have to cast the spell for the permanent buffs to not be lost on death in exchange for rare reagents. That way it is an optional feature and it is also documented now in the spell book.

**Comment by SuDmit** [comment]
New spell is level 8 which means it's post-Plantera... Just as State Lock, so it's generally same, except is cheaper for couple of uses and then more and more expensive as time (and deaths) goes.
May I suggest lowering required level for CoE to 5 (which is obtainable just at start of hardmode, just like resources for it and SL)? Or even combine State Lock and Cycle of Eternity into single spell, which is available earlier, unlocked by Dao of Pow, and does what CoE does, and at level 8 is upgraded to SL? What do you think?

**Comment by Aurocosh** [comment]
Changed level of this spell from 8 to 5 in version 0.8.3.7. It was never supposed to be this high and was intended to be level 4 or 5. Fixed it in new version. 

I am not gonna merge State Lock and Cycle of Eternity into one spell. They pretty different purposes. One is prevents loss of all buffs temporarily, while another is just a convenient and permanent way no not recast all eternal spells after death.

Also adjusted cost of the Cycle of Eternity, made it cheaper. It now costs 20 to cast instead of 50 and consumes 2 rare reagents per one eternal buff. When setting cost i kinda forgot that the State lock spell has 5 charges and cost per death is only 1/5 of the original cost.
